/// Service to provide daily inspirational quotes
class DailyQuotesService {
  // Deterministic quote based on user ID and date
  String getQuoteForToday(String userId, DateTime date) {
    if (_quotes.isEmpty) return "Have a wonderful day!";

    // Create a deterministic index ensuring the same user sees the same quote on the same day,
    // but different users might see different quotes (depending on the hash).
    // Using day of year to rotate daily.
    final dayOfYear = int.parse(
      "${date.year}${date.month.toString().padLeft(2, '0')}${date.day.toString().padLeft(2, '0')}",
    );
    final seed = userId.hashCode + dayOfYear;
    final index = seed.abs() % _quotes.length;

    return _quotes[index];
  }

  // Hardcoded list of wellness and positivity quotes
  static const List<String> _quotes = [
    "Every day is a new beginning. Take a deep breath and start again.",
    "You are capable of amazing things.",
    "Today is a good day to have a good day.",
    "Believe you can and you're halfway there.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Positive anything is better than negative nothing.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "It is never too late to be what you might have been.",
    "Do what you can, with what you have, where you are.",
    "Happiness is not something ready made. It comes from your own actions.",
    "You are never too old to set another goal or to dream a new dream.",
    "Health is the greatest gift, contentment the greatest wealth.",
    "A healthy outside starts from the inside.",
    "To keep the body in good health is a duty.",
    "Your body hears everything your mind says.",
    "Wellness is the complete integration of body, mind, and spirit.",
    "Self-care is not selfish. You cannot serve from an empty vessel.",
    "Small steps in the right direction can turn out to be the biggest step of your life.",
    "Don't count the days, make the days count.",
    "Aging is just another word for living.",
    "The best way to predict the future is to create it.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "The longer I live, the more beautiful life becomes.",
    "Wisdom comes with winters.",
    "Gray hair is a crown of glory; it is gained in a righteous life.",
    "Cherish every moment and every person in your life.",
    "Family is where life begins and love never ends.",
    "The love of family and the admiration of friends is much more important than wealth and privilege.",
    "Call a loved one today; their voice is medicine for the soul.",
    "You are loved more than you know.",
    "A friend is what the heart needs all the time.",
    "Laughter is timeless, imagination has no age, and dreams are forever.",
    "Smile, it's free therapy.",
    "A good laugh is sunshine in the house.",
    "Peace begins with a smile.",
    "Let your smile change the world, but don't let the world change your smile.",
    "Walking is man's best medicine.",
    "Take care of your body. It's the only place you have to live.",
    "Movement is a medicine for creating change in a person's physical, emotional, and mental states.",
    "Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit.",
    "Sleep is the best meditation.",
    "Eat well, move daily, hydrate often, sleep lots, love your body.",
    "Your health is an investment, not an expense.",
    "Gratitude turns what we have into enough.",
    "Enjoy the little things, for one day you may look back and realize they were the big things.",
    "Today, be the reason someone feels loved.",
    "Kindness is a language which the deaf can hear and the blind can see.",
    "Act as if what you do makes a difference. It does.",
    "The purpose of our lives is to be happy.",
    "Life is short, and it is here to be lived.",
    "Turn your wounds into wisdom.",
    "Tough times never last, but tough people do.",
    "You don't have to be perfect to be amazing.",
    "Focus on the step in front of you, not the whole staircase.",
    "One day at a time.",
    "This too shall pass.",
    "Your mind is a garden. Your thoughts are the seeds. You can grow flowers or you can grow weeds.",
    "Stay close to people who feel like sunlight.",
    "You are strong, you are beautiful, you are enough.",
    "Embrace the glorious mess that you are.",
    "Life isn't about waiting for the storm to pass, it's about learning to dance in the rain.",
    "Every moment is a fresh beginning.",
    "Breathe. It's just a bad day, not a bad life.",
    "Stars can't shine without darkness.",
    "Hope is the heartbeat of the soul.",
    "The best is yet to be.",
    "Wrinkles should merely indicate where smiles have been.",
    "Beauty is not in the face; beauty is a light in the heart.",
    "Count your age by friends, not years. Count your life by smiles, not tears.",
    "Someone is thinking of you right now.",
    "You make the world a better place just by being in it.",
    "Your life has purpose and meaning.",
    "Listen to the wind, it talks. Listen to the silence, it speaks.",
    "Nature does not hurry, yet everything is accomplished.",
    "Look deep into nature, and then you will understand everything better.",
    "Sunrise is God's way of saying, 'Let's start again'.",
    "Keep looking up! I learn from the past, dream about the future and look up.",
    "Memory is the diary that we all carry about with us.",
    "We do not remember days, we remember moments.",
    "Life is about creating and living experiences that are worth sharing.",
    "Your story is unique and worth telling.",
    "Be kind to yourself today.",
    "Forgive yourself for not knowing what you didn't know before you learned it.",
    "Talk to yourself like you would to someone you love.",
    "You are doing the best you can.",
    "It's okay to take a break.",
    "Drink some water today.",
    "Take your medication on time, it helps you stay strong.",
    "Eat a fruit today.",
    "Stretch your arms and legs.",
    "Take a short walk if you can.",
    "Listen to your favorite song today.",
    "Read a few pages of a good book.",
    "Do a puzzle or a brain game.",
    "Learn something new today.",
    "Curiosity is the wick in the candle of learning.",
    "An investment in knowledge pays the best interest.",
    "The heart that loves is always young.",
    "Love is the only gold.",
    "Where there is love there is life.",
    "Let love be your guide.",
    "Spread love everywhere you go.",
    "The simpler we make our lives, the less we have to worry about.",
    "Simplicity is the ultimate sophistication.",
    "Clutter is nothing more than postponed decisions.",
    "Collect moments, not things.",
    "Time fits all things.",
    "Patience is bitter, but its fruit is sweet.",
    "Good things happen to those who wait.",
    "Everything comes to you at the right time.",
    "Trust the timing of your life.",
    "Optimism is the faith that leads to achievement.",
    "Choose to be optimistic, it feels better.",
    "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.",
    "Attitude is a little thing that makes a big difference.",
    "Your attitude determines your direction.",
    "Excellence is not a skill. It is an attitude.",
    "Do what makes your soul shine.",
    "Follow your bliss.",
    "Find joy in the ordinary.",
    "There is beauty all around you.",
    "Open your eyes to the wonder of the world.",
    "Life is a party. Dress like it.",
    "Age is an issue of mind over matter. If you don't mind, it doesn't matter.",
    "Old age is like everything else. To make a success of it, you've got to start young.",
    "Youth is the gift of nature, but age is a work of art.",
    "The afternoon of life is just as full of meaning as the morning.",
    "Don't regret growing older. It is a privilege denied to many.",
    "Live your life and forget your age.",
    "You are as young as your faith, as old as your doubt.",
    "Stay young at heart.",
    "There is a fountain of youth: it is your mind, your talents, the creativity you bring to your life.",
    "Creativity takes courage.",
    "Every artist was first an amateur.",
    "Paint your own picture of life.",
    "Sing like no one is listening.",
    "Dance like nobody's watching.",
    "Love like you've never been hurt.",
    "Live like it's heaven on earth.",
    "The best preparation for tomorrow is doing your best today.",
    "Quality is not an act, it is a habit.",
    "Well done is better than well said.",
    "Actions speak louder than words.",
    "Be the change that you wish to see in the world.",
    "In a gentle way, you can shake the world.",
    "No act of kindness, no matter how small, is ever wasted.",
    "Kindness makes you the most beautiful person in the world.",
    "Compassion is the basis of morality.",
    "We rise by lifting others.",
    "Alone we can do so little; together we can do so much.",
    "Unity is strength.",
  ];
}
